config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    :sessions => 'users/sessions',
    :registrations =>"users/registrations",
    :passwords => "users/passwords",
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:"customer/portal#index"
  mount ActionCable.server => "/cable"
  mount Ims::Inv::Interface => 'wqj'
  get "/application/menus",to:"application#menus"
  get "/application/templates",to:"application#templates"
  resources :interfaces do
    collection do
      put :reset_passwords
      post :stringify_base64_img
      get :gzh
      get :get_prescriptions_by_phone
      get :get_all_prescriptions_by_phone
      get :get_not_read_prescription
      post :refund_order
      get :get_orders
      post :pay_order
      post :save_order
      post :cancel_order
      get :get_prescriptions_cart
      get :set_prescriptions_cart
      get :set_current_pharmacy
      get :get_current_pharmacy
      get :get_pharmacy
      get :get_yanzhengma
      get :get_duanxinma
      get :get_dicts
      get :get_addrs
      get :get_medicine_by_name
      post :generate_pdf # 生成pdf
    end
  end
  ############################
  ########### admin ##########
  namespace :admin do
    resources :home
    resources :organizations
    resources :users
  end
  namespace :healthcloud do
    resources :home do
      collection do
        get :templates
      end
    end
    resources :partner_accounts do 
      collection do
        get :pictures
        post :set_ws_sys
        delete :def_ws_sys
        put :update_ws_sys
        get :find_test
        get :get_date_by_id
        get :get_last_data
      end
    end
  end
  ########### admin ##########
  ############################

  ############################
  ########### customer 个人中心 客户 ##########
  namespace :customer do
    resources :home do
      collection do
        get :prescriptions
        get :prescription
        get :orders
        get :order
        get :confirm_order
        get :feedbacks
        get :edit_password
        put :save_password
        get :forget_password
        get :coupons
        get :get_coupons
      end
    end
    resources :portal do
      collection do
        
        # get :pullrefresh_main
        # get :pullrefresh_sub
        # get :full_screen

        get :map
        get :settlement
        get :pay
      end
    end
    resources :report do
      collection do
        get :pay
        post :pay_order
        post :valid_pay_status
        get :qrcode
        get :show_guide_flag
        get :hide_guide
        get :advise
        get :orders
      end
    end
    resources :invoice_headers
    resources :feedbacks do
      collection do
        get :get_cur_feedbacks
      end
    end
  end
  ########### customer ##########
  ############################

  ############################
  ########### hospital ##########
  namespace :hospital do
    namespace :sets do
      resources :inis do
        collection do
          get :cur_org_ini
          get :get_org_user_list
        end
      end
      resources :departments do 
        collection do 
          get :get_active_departments
          post :set_cur_department
        end
      end
      # 医嘱模板管理
      resources :mtemplates do 
        collection do
          post :quote_template
        end
      end

      # 编码表
      resources :codes do
        collection do
          get :get_code_by_system
        end
      end 
    end

    namespace :dict do
      resources :new_medications do
        collection do 
          get :list
        end
      end
    end
    resources :home
    # 就诊管理、统计
    resources :encounters do 
      collection do 
        post :quote_orders
      end
      member do
        get :all_prescriptions
      end
    end
    resources :orders      # 药品
    # 处方
    resources :prescriptions do
      collection do
        # get :get_all_prescriptions_by_phone
        # get :get_prescriptions_by_phone
        # get :get_not_read_prescription
        # put :read_prescription
      end
      member do
        post :set_drug_store
      end
    end
    resources :histories      # 历史列表

    # 诊断
    resources :diagnoses do
      collection do
        post :sort
      end
    end

    resources :patients do 
      collection do
        get :get_encounters_by_person_id
      end
    end
    resources :people
  end
  ########### hospital ##########
  ############################


  ############################
  ########### dict ##########
  namespace :dict do
    resources :diseases  # 诊断字典
    resources :medications #药品字典
  end
  ########### dict ##########
  ############################


  ############################
  ########### ims ##########
  namespace :ims do
    resources :home
    resources :orders do
      collection do
        get :get_orders         # 获取订单
        get :get_order          # 获取订单
        get :get_prescriptions  # 获取处方信息
        get :get_prescription   # 获取处方信息 
        get :charging_pre       # 收费
        get :dispensing_order   # 发药
        get :return_order       # 退药
        get :oprate_order       # 订单操作(发药/退药、、)
        get :order_settings
        get :get_detail
        get :get_search_data    # 未发订单或处方检索
        get :get_order_by_code  # 已发药或已退订单检索  
        post :operat_order_by_prescription   # 平台处方收费或收费并发药操作
        get :return_drug           # 退药
        get :return_amount           # 退费
        get :prescription_back     # 下载错误处方返回      
        post :create_order  #生成订单
        post :order_setting  #订单设置
      end
    end

    # 设置
    resources :settings do
      collection do
        get :get_cur_set
        post :save_settings
      end
    end

    # 药品管理
    resources :items do
      collection do
        get :get_items
        get :juzi_to_jp_wb #句子转简拼  五笔
        post :change_status
        post :delete_item
        post :save_item
      end
    end
    
    # 统计
    resources :reports do
      collection do
        get :sale_report                          # 销售统计
        get :dispensed_hospital                   # 处方发药汇总-医院
        get :dispensed_name                       # 处方发药汇总-发药人
        get :dispensed_hospital_and_name          # 处方发药汇总-医院及发药人
        get :dispensed_name_and_hospital          # 处方发药汇总-发药人及医院
        get :returned_hospital                    # 处方退药汇总-医院
        get :returned_name                        # 处方退药汇总-发药人
        get :returned_hospital_and_name           # 处方退药汇总-医院及发药人
        get :returned_name_and_hospital           # 处方退药汇总-发药人及医院
        get :drug_report                          # 处方药品汇总表
        get :drug_dispensed_report                # 处方发药汇总表
        get :drug_returned_report                 # 处方退药汇总表
        get :drug_dispensed_fact                  # 处方发药汇总-厂家
        get :drug_returned_fact                   # 处方退药汇总-厂家
        get :order_static                         # 订单统计(针对未交费、待发药)

        post :report_detail                       # 报表查看明细
      end
    end

    # 库存
    namespace :inv do
      resources :stocks do
        collection do
          get :search_stocks                          # 库存查询
          get :exports                                # 库存导入保存
          post :upload_file                           # 库存表上传
        end
      end

      resources :refresh_logs do
        collection do
          post :get_log                               # 查詢日誌
        end
      end
    end

    resources :interfaces do
      collection do
      end
    end
  end
  ########### ims ##########
  ############################

  ########### hujun_start ##########
  # match '/users/positions/baidu', to: 'positions#baidu', via: [:get]
  match '/pay/wechat', to: 'pay#wechat', via: [:post]
  match '/pay/alipay', to: 'pay#alipay', via: [:post]

  match '/pay/confirm/:id', to: 'pay#confirm', via: [:get]
  match '/pay/index',       to: 'pay#index',   via: [:get]
  match '/pay/wx/pay',      to: 'pay#wx',      via: [:post]
  match '/pay/ali/pay',     to: 'pay#ali',     via: [:post]

  match '/refund/wechat', to: 'refund#wechat', via: [:post]
  match '/refund/alipay', to: 'refund#alipay', via: [:post]

  match '/wechat/login',      to: 'wechat#login',     via: [:get]
  match '/wechat/public_pay', to: 'wechat#pay',       via: [:post]
  match '/wechat/websocket',  to: 'wechat#websocket', via: [:get]
  match '/wechat/info',       to: 'wechat#info',      via: [:post]
  match '/wechat/push_wowgo', to: 'wechat#wowgo',     via: [:post]
  match '/wechat/send_data',  to: 'wechat#send_data', via: [:post]
  ########### hujun_end   ##########
end

app/models/hospital/order.rb
class Hospital::Order < ApplicationRecord

  belongs_to :encounter, class_name: '::Hospital::Encounter', foreign_key: 'encounter_id', optional: true
  # has_one :dict_medication, class_name: '::Hospital::Dict::NewMedication', foreign_key: 'serialno' 

  belongs_to :prescription, class_name: '::Hospital::Prescription', foreign_key: 'prescription_id', optional: true
  belongs_to :author, class_name: '::User', foreign_key: 'author_id', optional: true
  belongs_to :mtemplate, class_name: '::Hospital::Sets::Mtemplate', foreign_key: 'mtemplate_id', optional: true
  # order_type 医嘱类型 1 药品医嘱

  validate :enough_storage?

  # 保存前验证库存量
  def enough_storage?
    # 根据药品id 获取药品库存的方法
    # cur_drug_storage = 5.times.map { |e| rand(8)  }.sort {|x,y| y <=> x}

    cur_drug_storage = [::Hospital::Dict::NewMedication.find(self.serialno).quantity]
    p cur_drug_storage
    p (cur_drug_storage[0] || 0) < self.total_quantity.to_f
    if (cur_drug_storage[0] || 0) < self.total_quantity.to_f
      errors.add(:total_quantity, "保存失败： 医嘱药品总量超过最大库存量 ")
    end
  end

  def initialize args = {}
    super args
    self.status = 0
    self.type_type ||= 'instance'
  end


  def dict_medication
    ::Dict::Medication.find(self.serialno) rescue nil
  end

  def to_web_front_with_photo
    ret = {
      id: self.id,
      serialno: self.serialno,
      picture: self.dict_medication&.picture,
      title: self.title,
      specification: self.specification,
      single_qty: {
        value: self.single_qty_value,
        unit: self.single_qty_unit
      },
      dose: {
        value:self.dose_value,
        unit: self.dose_unit
      },
      route:{
        code: self.route_code,
        display: self.route_display
      },
      frequency:{
        code: self.frequency_code,
          display: self.frequency_display
      },
      course_of_treatment:{
        value: self.course_of_treatment_value,
        unit: self.course_of_treatment_unit
      },
      formul: {
        code: self.formul_code,
        display: self.formul_display
      },
      total_quantity: self.total_quantity,
      unit: self.unit,
      price: self.price,
      total_price: self.price * self.total_quantity,
      note: self.note,
      status: self.status,
      order_type: self.order_type,
      encounter_id: self.encounter_id,
      author: {
        id: self.author.id,
        display: self.author.name
      },
      factory_name: self.factory_name,
      base_unit: self.base_unit,
      mul: self.mul,
      measure_val: self.measure_val,
      measure_unit: self.measure_unit,
      type_type: self.type_type
    }
  end

  def to_web_front
    ret = {
      id: self.id,
      serialno: self.serialno,
      title: self.title,
      specification: self.specification,
      single_qty: {
        value: self.single_qty_value,
        unit: self.single_qty_unit
      },
      dose: {
        value:self.dose_value,
        unit: self.dose_unit
      },
      route:{
        code: self.route_code,
        display: self.route_display
      },
      frequency:{
        code: self.frequency_code,
          display: self.frequency_display
      },
      course_of_treatment:{
        value: self.course_of_treatment_value,
        unit: self.course_of_treatment_unit
      },
      formul: {
        code: self.formul_code,
        display: self.formul_display
      },
      total_quantity: self.total_quantity,
      unit: self.unit,
      price: self.price,
      total_price: self.price * self.total_quantity,
      note: self.note,
      status: self.status,
      order_type: self.order_type,
      encounter_id: self.encounter_id,
      author: {
        id: self.author.id,
        display: self.author.name
      },
      factory_name: self.factory_name,
      base_unit: self.base_unit,
      mul: self.mul,
      measure_val: self.measure_val,
      measure_unit: self.measure_unit,
      type_type: self.type_type
    }
  end

  class<<self
    def can_to_prescription?(order_ids)
      cur_order_status = ::Hospital::Order.find(order_ids).map { |e| e.status  }
      cur_order_status.uniq! 
      p cur_order_status
      if cur_order_status.size == 1 && cur_order_status[0] == 0 # 还是新建状态的医嘱就能创建处方
        true
      else
        false
      end
    end

    def copy_orders(order_ids, encounter_id, cur_user, selects: {type_type: "instance"})
      cur_encounter = ::Hospital::Encounter.find(encounter_id)
      cur_orders = ::Hospital::Order.find(order_ids)
      errors = []
      ::ActiveRecord::Base.transaction do 
        cur_orders.each do |_order|
          # 三方面复制  复制药品使用信息  复制当前药品的价格  置空相关医嘱和人相关的信息
          # 查询当前药品使用信息
          cur_medication = ::Dict::Medication.find(_order.serialno)
          unless cur_medication.can_create?
            errors << "药品: #{_order.title} 未启用" 
            next
          end
          medication_info = cur_medication.to_order_info
          new_order_args = {
              single_qty_value: _order.single_qty_value,
              single_qty_unit: _order.single_qty_unit,
              dose_value: _order.dose_value,
              dose_unit: _order.dose_unit,
              route_code: _order.route_code,
              route_display: _order.route_display,
              frequency_code: _order.frequency_code,
              frequency_display: _order.frequency_display,
              course_of_treatment_value: _order.course_of_treatment_value,
              course_of_treatment_unit: _order.course_of_treatment_unit,
              total_quantity: _order.total_quantity,
              order_type: _order.order_type,
              status: 0,
              encounter_id: encounter_id,
              author_id: cur_user.id,
              prescription_id: nil,
              type_type: (selects[:type_type] || _order.type_type)
          }
          new_order_args.merge!(medication_info)
          new_order = ::Hospital::Order.create!(new_order_args)
        end
      end
      if errors.blank?
        {flag: true, info: "success"}
      else
        {flag: false, info: errors.join("、")}
      end
    end

    def to_template_order(order_ids, mtemplate_id, cur_user)
      cur_orders = ::Hospital::Order.find(order_ids)
      ::ActiveRecord::Base.transaction do 
        cur_orders.each do |_order|
          if _order.type_type == "template"
            # 如果是模板医嘱就直接创建关系  不做复制
            _order.mtemplate_id = mtemplate_id
            _order.save!
            next
          end
          # 三方面复制  复制药品使用信息  复制当前药品的价格  置空相关医嘱和人相关的信息
          # 查询当前药品使用信息
          cur_medication = ::Dict::Medication.find(_order.serialno)
          raise "创建失败  有药品不能使用" unless cur_medication.can_create?
          medication_info = cur_medication.to_order_info
          new_order_args = {
              single_qty_value: _order.single_qty_value,
              single_qty_unit: _order.single_qty_unit,
              dose_value: _order.dose_value,
              dose_unit: _order.dose_unit,
              route_code: _order.route_code,
              route_display: _order.route_display,
              frequency_code: _order.frequency_code,
              frequency_display: _order.frequency_display,
              course_of_treatment_value: _order.course_of_treatment_value,
              course_of_treatment_unit: _order.course_of_treatment_unit,
              total_quantity: _order.total_quantity,
              order_type: _order.order_type,
              status: 0,
              author_id: cur_user.id,
              mtemplate_id: mtemplate_id,
              type_type:"template"
          }
          new_order_args.merge!(medication_info)
          new_order = ::Hospital::Order.create!(new_order_args)
        end
      end
    end

    def can_create?(encounter_id)
      cur_encounter = ::Hospital::Encounter.find(encounter_id) rescue nil
      return {flag: false, info:"无效就诊id"}if cur_encounter.nil?
      # 判断是否存在诊断  存在诊断就能创建 医嘱
      if cur_encounter.diagnoses.present?
        return {flag: true, info: "success"}
      else
        return {flag: false, info: "请先下诊断"}
      end
    end
  end
end

app/models/ims.rb
module Ims
  def self.table_name_prefix
    'ims_'
  end
end

app/models/ims/get_data.rb
#encoding: utf-8
require 'mysql2'
class Ims::GetData < ApplicationRecord
	class << self
		# 执行存储过程
		def find_data args={}
			begin
				# client = Mysql2::Client.new(:host => "192.168.2.207",:username => "root",:password => "Tenmind@207",:port => "3306",:database => "mmp")
				# client = Mysql2::Client.new(:host => "192.168.2.207",
		  #                           :username => "root",
		  #                           :password => "Tenmind@207",
		  #                           :port => "3306",
		  #                           :database => "mmp_lgl"
		  #                           )
				# sql = "select code,name,py from dictarea limit 5";
				sql = "CALL p_getYPDataList('#{args[:search]}',#{args[:i_days]},'#{args[:org_id]}');"
				p sql
				# result = client.query(sql).to_a 
				result = Ims::PreHeader.find_by_sql(sql)
				JSON.parse(result.to_json)
			rescue Exception => e
				print e.message rescue "  e.messag----"
        print "laaaaaaaaaaaaaaaaaaaa 执行存储过程 出错: " + e.backtrace.join("\n")
        result = {flag:false,:info=>"药店系统出错。"}
        []
			end
		end
	end

end

app/views/ims/orders/_form.html.erb
<%= form_with(model: ims_order, local: true) do |form| %>
  <% if ims_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ims_order.errors.count, "error") %> prohibited this ims_order from being saved:</h2>

      <ul>
      <% ims_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :source_org_ii %>
    <%= form.text_field :source_org_ii, id: :ims_order_source_org_ii %>
  </div>

  <div class="field">
    <%= form.label :source_org_name %>
    <%= form.text_field :source_org_name, id: :ims_order_source_org_name %>
  </div>

  <div class="field">
    <%= form.label :target_org_ii %>
    <%= form.text_field :target_org_ii, id: :ims_order_target_org_ii %>
  </div>

  <div class="field">
    <%= form.label :target_org_name %>
    <%= form.text_field :target_org_name, id: :ims_order_target_org_name %>
  </div>

  <div class="field">
    <%= form.label :patient_order_id %>
    <%= form.text_field :patient_order_id, id: :ims_order_patient_order_id %>
  </div>

  <div class="field">
    <%= form.label :order_code %>
    <%= form.text_field :order_code, id: :ims_order_order_code %>
  </div>

  <div class="field">
    <%= form.label :patient_name %>
    <%= form.text_field :patient_name, id: :ims_order_patient_name %>
  </div>

  <div class="field">
    <%= form.label :repeat_number %>
    <%= form.text_field :repeat_number, id: :ims_order_repeat_number %>
  </div>

  <div class="field">
    <%= form.label :total_amount %>
    <%= form.text_field :total_amount, id: :ims_order_total_amount %>
  </div>

  <div class="field">
    <%= form.label :search_name %>
    <%= form.text_field :search_name, id: :ims_order_search_name %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_field :note, id: :ims_order_note %>
  </div>

  <div class="field">
    <%= form.label :operater %>
    <%= form.text_field :operater, id: :ims_order_operater %>
  </div>

  <div class="field">
    <%= form.label :operat_at %>
    <%= form.datetime_select :operat_at, id: :ims_order_operat_at %>
  </div>

  <div class="field">
    <%= form.label :ori_id %>
    <%= form.text_field :ori_id, id: :ims_order_ori_id %>
  </div>

  <div class="field">
    <%= form.label :ori_code %>
    <%= form.text_field :ori_code, id: :ims_order_ori_code %>
  </div>

  <div class="field">
    <%= form.label :created_at %>
    <%= form.datetime_select :created_at, id: :ims_order_created_at %>
  </div>

  <div class="field">
    <%= form.label :updated_at %>
    <%= form.datetime_select :updated_at, id: :ims_order_updated_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ims/orders/edit.html.erb
<h1>Editing Ims Order</h1>

<%= render 'form', ims_order: @ims_order %>

<%= link_to 'Show', @ims_order %> |
<%= link_to 'Back', ims_orders_path %>

app/views/ims/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ims Orders</h1>

<table>
  <thead>
    <tr>
      <th>Source org ii</th>
      <th>Source org name</th>
      <th>Target org ii</th>
      <th>Target org name</th>
      <th>Patient order</th>
      <th>Order code</th>
      <th>Patient name</th>
      <th>Repeat number</th>
      <th>Total amount</th>
      <th>Search name</th>
      <th>Note</th>
      <th>Operater</th>
      <th>Operat at</th>
      <th>Ori</th>
      <th>Ori code</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ims_orders.each do |ims_order| %>
      <tr>
        <td><%= ims_order.source_org_ii %></td>
        <td><%= ims_order.source_org_name %></td>
        <td><%= ims_order.target_org_ii %></td>
        <td><%= ims_order.target_org_name %></td>
        <td><%= ims_order.patient_order_id %></td>
        <td><%= ims_order.order_code %></td>
        <td><%= ims_order.patient_name %></td>
        <td><%= ims_order.repeat_number %></td>
        <td><%= ims_order.total_amount %></td>
        <td><%= ims_order.search_name %></td>
        <td><%= ims_order.note %></td>
        <td><%= ims_order.operater %></td>
        <td><%= ims_order.operat_at %></td>
        <td><%= ims_order.ori_id %></td>
        <td><%= ims_order.ori_code %></td>
        <td><%= ims_order.created_at %></td>
        <td><%= ims_order.updated_at %></td>
        <td><%= link_to 'Show', ims_order %></td>
        <td><%= link_to 'Edit', edit_ims_order_path(ims_order) %></td>
        <td><%= link_to 'Destroy', ims_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ims Order', new_ims_order_path %>

app/views/ims/orders/new.html.erb
<h1>New Ims Order</h1>

<%= render 'form', ims_order: @ims_order %>

<%= link_to 'Back', ims_orders_path %>

app/views/ims/orders/order_settings.html.erb
<style type="text/css">
#ims_setting_div{background-color: rgb(244, 245, 229);}
input{opacity: 0.8;}
.page-header {
  font-family: Consolas, "Microsoft YaHei", "Microsoft JhengHei";
  padding: 0;
  margin: 0 0 16px 0;
}
.page-header > i {
  margin-left: 0px;
}
.page-header > h3 {
  margin: 0;
  float: right;
  display: inline-block;
  width: -webkit-calc(100% - 80px);
  width: -moz-calc(100% - 80px);
  width: calc(100% - 80px);
}
.page-header > h3 > small {
  margin-top: 8px;
  display: block;
  font-size: 14px;
  width: 100%;
  overflow: hidden;
  white-space: nowrap;
}
#submit_btn{
	position: fixed;
	top: 64px;
	right: 12px;
}
</style>
<template id="ims_setting_div">
	<div id="prescription_setting_div">
	  <article class="page-header" style="border-bottom: 1px solid #ddd;">
	    <i class="fa fa-cogs fa-fw fa-3x"></i>
	    <h3>药店设置<small>药店设置</small></h3>
	    <div class="header-right-btns">
	   </div>
	  </article>

		<el-form size="mini" :rules="rules" :model="setting" ref="settingForm" label-width="100px">
			<el-row>
		  	<el-col :span="10">
		  		<el-form-item
				    label="付费未取药过期天数"
				    prop="validity">
				    <!-- <el-input v-model="setting.validity" auto-complete="off"> -->
			    	<el-input v-model="setting.validity" auto-complete="off" name="ims_setting[payment_expired]">

					    <span>天</span>
					  </el-input>
				  </el-form-item>

				<el-form-item
				    label="未支付订单过期天数"
				    prop="validity">
				    <!-- <el-input v-model="setting.validity" auto-complete="off"> -->
			    	<el-input v-model="setting.validity" auto-complete="off" name="ims_setting[unpaid_expired]">
					    <span>天</span>
					  </el-input>
				  </el-form-item>

				  <el-form-item
				    label="语音提示"
				    prop="voice">
				  	<!-- <el-select v-model="setting.voice" value-key="code" placeholder="请选择"> -->
			  		<el-select v-model="setting.voice" value-key="code" placeholder="请选择" name="ims_setting[voice_prompts]">
					    <el-option
					      v-for="item in options"
					      :key="item.value"
					      :label="item.label"
					      :value="item.value">
					    </el-option>
					  </el-select>
				  </el-form-item>

				</el-col>

				<el-col :span="24">
				  <el-form-item>
				    <el-button id="submit_btn" type="primary" @click="submitForm('settingForm')">提交</el-button>
				  </el-form-item>
				</el-col>
			</el-row>
		</el-form>
	</div>

</template>

<script type="text/javascript">
window.current_template_obj = {
	data: function(){
		return {
			activeCollapse: "settings",
			setting: {}, // 
			options:[{value:"yes",label:"是"},{value:"no",label:"否"}],
			settingsResource: Vue.resource('/ims/settings{/id}.json'),
			rules: {
				validity: [
		      { required: true, message: '效期不能为空'},
		    ],
				voice: [
		      { required: true, message: '请选择语音'},
		    ]
			}
		}
	},
	watch: {
	},
	mounted: function () {
		this.$nextTick(function(){
			this.init();
		})
	},
	methods: {
		init: function() {
			console.log(this.$parent.common_data_voices)
			console.log(this.voices)
		},
		submitForm: function (formName) {
      this.$refs[formName].validate( function (valid) {
        if (valid) {
          alert('submit!');
        } else {
          console.log('error submit!!');
          return false;
        }
      });
    },
    resetForm: function (formName) {
      this.$refs[formName].resetFields();
    },
    // 判断年龄，如果小于14要求出生日期、监护人必填
    judgeAge: function (val) {
    	var _this = this;
    	_this.$message({
        message: "请输入具体的出生日期、监护人姓名。",
        type: 'warning'
      });
    	_this.rules["birth_date"][0]["required"] = true;
    },
		// 侧边搜索患者栏目
		toggleSidebar: function () {
			console.log("搜索患者侧边栏")
		},
		// 判断性别，根据性别显示图标
  	judgevoice: function (voice) {
  		if(!voice){ voice = ""; }
      var html = '';
  		if(voice.indexOf('男')>-1){
  			html = '<i class="text-primary fa fa-lg fa-fw fa-male"></i>';
  		}else if(voice.indexOf('女')>-1){
  			html = '<i class="text-danger fa fa-lg fa-fw fa-female"></i>';
  		}else{
  			html = '<i class="text-muted fa fa-lg fa-fw fa-male"></i>'
  		}
  		return html;
	  },
	}
}
</script>

app/views/ims/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Source org ii:</strong>
  <%= @ims_order.source_org_ii %>
</p>

<p>
  <strong>Source org name:</strong>
  <%= @ims_order.source_org_name %>
</p>

<p>
  <strong>Target org ii:</strong>
  <%= @ims_order.target_org_ii %>
</p>

<p>
  <strong>Target org name:</strong>
  <%= @ims_order.target_org_name %>
</p>

<p>
  <strong>Patient order:</strong>
  <%= @ims_order.patient_order_id %>
</p>

<p>
  <strong>Order code:</strong>
  <%= @ims_order.order_code %>
</p>

<p>
  <strong>Patient name:</strong>
  <%= @ims_order.patient_name %>
</p>

<p>
  <strong>Repeat number:</strong>
  <%= @ims_order.repeat_number %>
</p>

<p>
  <strong>Total amount:</strong>
  <%= @ims_order.total_amount %>
</p>

<p>
  <strong>Search name:</strong>
  <%= @ims_order.search_name %>
</p>

<p>
  <strong>Note:</strong>
  <%= @ims_order.note %>
</p>

<p>
  <strong>Operater:</strong>
  <%= @ims_order.operater %>
</p>

<p>
  <strong>Operat at:</strong>
  <%= @ims_order.operat_at %>
</p>

<p>
  <strong>Ori:</strong>
  <%= @ims_order.ori_id %>
</p>

<p>
  <strong>Ori code:</strong>
  <%= @ims_order.ori_code %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @ims_order.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @ims_order.updated_at %>
</p>

<%= link_to 'Edit', edit_ims_order_path(@ims_order) %> |
<%= link_to 'Back', ims_orders_path %>